name: Pipeline de Despliegue

on:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      - name: Simulaci贸n de build
        run: echo "Construyendo y probando el proyecto..."

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Despliegue en Dev
        run: echo "Desplegando en el entorno de Desarrollo..."

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Despliegue en Producci贸n
        run: echo "Desplegando en el entorno de Producci贸n..."
